CREATE SCHEMA "DATA WAREHOUSE";

CREATE TABLE "DATA WAREHOUSE".TIEMPO(
    DateKey DOUBLE PRECISION NOT NULL,
    "Date" TIMESTAMP NOT NULL,   
    FiscalYear TEXT NOT NULL,   
    FiscalQuarter TEXT NOT NULL,
    "Month" TEXT NOT NULL,   
    FullDate TEXT NOT NULL,
    MonthKey DOUBLE PRECISION NOT NULL,
    CONSTRAINT "TIEMPO_PKEY" PRIMARY key (DateKey)
);

CREATE TABLE "DATA WAREHOUSE".SALES_TERRITORY(
    SalesTerritoryKey DOUBLE PRECISION NOT NULL,
    Region TEXT NOT NULL,
    Country TEXT NOT NULL,
    "Group" TEXT NOT NULL,
    CONSTRAINT "SALES_TERRITORY_PKEY" PRIMARY key (SalesTerritoryKey)
);

CREATE TABLE "DATA WAREHOUSE".SALES_ORDER(
    Channel TEXT NOT NULL,
    SalesOrderLineKey DOUBLE PRECISION NOT NULL,
    SalesOrder TEXT NOT NULL,
    SalesOrderLine TEXT NOT NULL,
CONSTRAINT "SALES_ORDER_PKEY" PRIMARY key (SalesOrderLineKey)
);

CREATE TABLE "DATA WAREHOUSE".RESELLER(
    ResellerKey DOUBLE PRECISION NOT NULL,
    ResellerID TEXT NOT NULL,
    BusinessType TEXT NOT NULL,
    Reseller TEXT NOT NULL,
    City TEXT NOT NULL,
    StateProvince TEXT NOT NULL,
    CountryRegion TEXT NOT NULL,
    PostalCode TEXT NOT NULL,
    CONSTRAINT "RESELLER_PKEY" PRIMARY key (ResellerKey)
);

CREATE TABLE "DATA WAREHOUSE".PRODUCT(
    ProductKey DOUBLE PRECISION NOT NULL,
    SKU TEXT NOT NULL,
    Product TEXT NOT NULL,
    StandardCost DOUBLE PRECISION NOT NULL,
    Color TEXT NOT NULL,
    ListPrice DOUBLE PRECISION NOT NULL,
    Model TEXT NOT NULL,
    Subcategory TEXT NOT NULL,
    Category TEXT NOT NULL,
    CONSTRAINT "PRODUCT_PKEY" PRIMARY key (ProductKey)
);


CREATE TABLE "DATA WAREHOUSE".CUSTOMER(
    CustomerKey DOUBLE PRECISION NOT NULL,
    CustomerID TEXT NOT NULL,
    Customer TEXT NOT NULL,
    City TEXT NOT NULL,
    StateProvince TEXT NOT NULL,
    CountryRegion TEXT NOT NULL,
    PostalCode TEXT NOT NULL,
    CONSTRAINT "CUSTOMER_PKEY" PRIMARY key (CustomerKey)
);

CREATE TABLE "DATA WAREHOUSE".SALES(
    SalesOrderLineKey DOUBLE PRECISION NOT NULL,
    ResellerKey DOUBLE PRECISION NOT NULL,
    CustomerKey DOUBLE PRECISION NOT NULL,
    ProductKey DOUBLE PRECISION NOT NULL,
    OrderDateKey DOUBLE PRECISION NOT NULL,
    DueDateKey DOUBLE PRECISION NOT NULL,
    ShipDateKey DOUBLE PRECISION,
    SalesTerritoryKey DOUBLE PRECISION NOT NULL,
    OrderQuantity DOUBLE PRECISION NOT NULL,
    UnitPrice DOUBLE PRECISION NOT NULL,
    ExtendedAmount DOUBLE PRECISION NOT NULL,
    UnitPriceDiscountPct DOUBLE PRECISION NOT NULL,
    ProductStandardCost DOUBLE PRECISION NOT NULL,
    TotalProductCost DOUBLE PRECISION NOT NULL,
    SalesAmount DOUBLE PRECISION NOT NULL,
);

-- AddForeignKey
ALTER TABLE "DATA WAREHOUSE".sales ADD CONSTRAINT "sales_SalesOrderLineKey_fkey" FOREIGN KEY (salesorderlinekey) REFERENCES "DATA WAREHOUSE".sales_order (salesorderlinekey) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "DATA WAREHOUSE".sales ADD CONSTRAINT "sales_ResellerKey_fkey" FOREIGN KEY (ResellerKey) REFERENCES "DATA WAREHOUSE".RESELLER(ResellerKey) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DATA WAREHOUSE".SALES ADD CONSTRAINT "sales_ProductKey_fkey" FOREIGN KEY (ProductKey) REFERENCES "DATA WAREHOUSE".PRODUCT(ProductKey) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DATA WAREHOUSE".SALES ADD CONSTRAINT "sales_CustomerKey_fkey" FOREIGN KEY (CustomerKey) REFERENCES "DATA WAREHOUSE".CUSTOMER(CustomerKey) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DATA WAREHOUSE".SALES ADD CONSTRAINT "sales_SalesTerritoryKey_fkey" FOREIGN KEY (SalesTerritoryKey) REFERENCES "DATA WAREHOUSE".SALES_TERRITORY(SalesTerritoryKey) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DATA WAREHOUSE".SALES ADD CONSTRAINT "sales_OrderDateKey_fkey" FOREIGN KEY (OrderDateKey) REFERENCES "DATA WAREHOUSE".TIEMPO(DateKey) ON DELETE CASCADE ON UPDATE CASCADE;

